### PR TITLE
stricter youtubedl format selectors

### LINKED ISSUE #3499: support imported HDR videos
Hi there!

It would be nice if HDR support was added to peertube.

Please see the attached image of how washed out colors are (even on a display without HDR) when importing a HDR video from youtube.

firefox_YugrianVGK

### LINKED ISSUE #3513: Import max resolution using youtube-dl
Steps to reproduce:

    Import https://www.youtube.com/watch?v=LXb3EKWsInQ

Describe the expected behavior

Video format should be 1080p max with 2160p deselected in peertube.

Actual behavior

Video format is 2160p max.

ficew4yquo

Additional information

    PeerTube instance:
        URL: https://vidrot.com
        version: git
        NodeJS version: 12
        Ffmpeg version: 4.3.1

    Browser name, version and platforms on which you could reproduce the bug: Firefox 84

### PR DESCRIPTION
**Pull request by rigelk**
## Description

Make sure selectors avoid av1 while importing videos, and otherwise match as closely to the maximum resolution enabled for transcoding to optimize download speed/necessary data.

## Related issues

fixes #3499 which discovered AV1 HDR videos that can be seldom found on YouTube are not supported by browsers, even after transcoding. Avoiding them is simpler for now than trying to find a colorspace transform to Rec. 709 at transcode-time.

fixes #3513 by capping the import download to the max supported resolution.

### CODE REVIEW

File: server/helpers/youtube-dl.ts [hunk 1]
```diff
@@ -8,6 +8,8 @@ import * as request from 'request'
 import { createWriteStream } from 'fs'
 import { CONFIG } from '@server/initializers/config'
 import { HttpStatusCode } from '../../shared/core-utils/miscs/http-error-codes'
+import { getEnabledResolutions } from '@server/controllers/api/config'
```
Comment (Chocobozzz) [inline server/helpers/youtube-dl.ts:11]: You must not import things from controllers

File: server/helpers/youtube-dl.ts [hunk 2]
```diff
@@ -92,13 +94,37 @@ function getYoutubeDLSubs (url: string, opts?: object): Promise<YoutubeDLSubs> {
   })
 }
 
+function downloadYoutubeDLVideoFormat () {
```
Comment (Chocobozzz) [inline server/helpers/youtube-dl.ts:97]: `getYoutubeDLVideoFormat`

**Comment by SimplyCorbett** [comment]
This fails when importing with the latest git:

  | Failed | 1/6/21, 10:13 PM
-- | -- | --
ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/eb79ce74c1d68fb50a85dd434046bcbb78ea8f9365df3d7ef2fd1fd0418028ec-import.mp4'

**Comment by SimplyCorbett** [comment]
I added this to the latest git and it fails on importing the video in #3499 


```
Job: 20 Type: video-import Processed on Jan 6, 2021, 10:16:25 PM Finished on Jan 6, 2021, 10:16:49 PM
--
{   "type": "youtube-dl",   "videoImportId": 20,   "generateThumbnail": false,   "generatePreview": false,   "fileExt": ".mp4" }
Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/eb79ce74c1d68fb50a85dd434046bcbb78ea8f9365df3d7ef2fd1fd0418028ec-import.mp4'


```

**Comment by rigelk** [comment]
@SimplyCorbett it works on my end 😕

**Comment by SimplyCorbett** [comment]
Reapplied, works. Must have either done it wrong or peertube doesn't like root uploading videos.

I'm still not sure what the best way to download pull requests is so I'm manually applying the patched files.. :)

**Comment by SimplyCorbett** [comment]
Nevermind, still failing. Some videos work and some don't.

**Comment by rigelk** [comment]
@SimplyCorbett gonna need those sweet sweet URLs :wink:

**Comment by SimplyCorbett** [comment]
https://www.youtube.com/watch?v=cw8ipUYodkE

Setup:

audio-only,240p,360p disabled.
480p,720p,1080p enabled.

4k enabled -> fail
4k disabled -> success

**Comment by rigelk** [comment]
Thanks @SimplyCorbett! I could reproduce the bug with 4k enabled, with the two videos above. It is because we only support `.mp4` files at import, and 2160p videos are only available in vp9 `.webm` once we exclude av1.

So either we downgrade or we support `.webm` files at import. Simple as that :)

**Comment by SimplyCorbett** [comment]
@rigelk Wouldn't it be easier to just download the highest resolution .mp4 available? 2160p being enabled doesn't mean every video has to be downloaded in 2160p :)

Webm support would be pretty cool though!

**Comment by rigelk** [comment]
We already "support" webm like any video format though. It's just that our preliminary request for file info specifies the `.webm` extension, because it can’t predict that a merge nor which merge will occur: https://stackoverflow.com/a/62065873/12767986

It’s just a matter of predicting which extension will result.

**Comment by rigelk** [comment]
@SimplyCorbett could you try on your end? I updated the PR with what I think should add support to `.webm` as well as any different extension from the video on YT triggered by a merge of video and audio formats.

**Comment by SimplyCorbett** [comment]
@rigelk It does download the 4k file correctly now but it downloads the washed out one so it's back to square one here.

https://www.youtube.com/watch?v=nhym0fLkEFg

stuff5

File: server/controllers/api/videos/import.ts [hunk 3]
```diff
@@ -219,9 +221,8 @@ async function addYoutubeDLImport (req: express.Request, res: express.Response)
     videoImportId: videoImport.id,
     generateThumbnail: !thumbnailModel,
     generatePreview: !previewModel,
-    fileExt: youtubeDLInfo.fileExt
-      ? `.${youtubeDLInfo.fileExt}`
-      : '.mp4'
+    fileExt: `.${youtubeDLInfo.ext || 'mp4'}`,
+    mergeExt: youtubeDLInfo.mergeExt && `.${youtubeDLInfo.mergeExt}`
```
Comment (Chocobozzz) [inline server/controllers/api/videos/import.ts:225]: I prefer to explicitly set the default option. If `youtubeDLInfo.mergeExt === ''` then we send `''` as option. A ternary would allow us to choose this default value (`undefined` for example).

File: server/controllers/api/videos/import.ts [hunk 4]
```diff
@@ -146,9 +146,11 @@ async function addYoutubeDLImport (req: express.Request, res: express.Response)
...
     logger.info('Cannot fetch information from import for URL %s.', targetUrl, { err })
 
-    return res.status(HttpStatusCode.BAD_REQUEST_400).json({
-      error: 'Cannot fetch remote information of this URL.'
-    }).end()
+    return res.status(HttpStatusCode.BAD_REQUEST_400)
+              .json({
+                error: 'Cannot fetch remote information of this URL.'
+              })
+              .end()
```
Comment (Chocobozzz) [inline server/controllers/api/videos/import.ts:153]: Please remove this `.end()`, we don't need it when we use `.json`

File: server/helpers/utils.ts [hunk 5]
```diff
@@ -86,6 +86,16 @@ function getUUIDFromFilename (filename: string) {
   return result[0]
 }
 
+function getEnabledResolutions (type: 'vod' | 'live') {
```
Comment (Chocobozzz) [inline server/helpers/utils.ts:89]: Put this in `lib/video-transcoding.ts` instead

File: server/helpers/youtube-dl.ts [hunk 6]
```diff
@@ -92,13 +103,40 @@ function getYoutubeDLSubs (url: string, opts?: object): Promise<YoutubeDLSubs> {
...
+    `bestvideo[vcodec!*=av01][vcodec!*=vp9.2][height=${resolution}]+bestaudio`, // case #2
+    `bestvideo[vcodec^=avc1][height<=${resolution}]+bestaudio[ext=m4a]`, // case #3
+    `bestvideo[vcodec!*=av01][vcodec!*=vp9.2]+bestaudio`,
+    'best[vcodec!*=av01][vcodec!*=vp9.2]' // case fallback
+  ].join('/')
+}
+
+function downloadYoutubeDLVideo (url: string, extension: string, timeout: number, mergeExtension?: string) {
   const path = generateVideoImportTmpPath(url, extension)
+  const finalPath = mergeExtension ? path.replace(extension, mergeExtension) : path
```
Comment (Chocobozzz) [inline server/helpers/youtube-dl.ts:134]: I think it's safer to use 

```
.replace(new RegExp(`${extension}$`), mergeExtension))
```

**Review by Chocobozzz — CHANGES_REQUESTED** [review]

File: server/controllers/api/videos/import.ts (hunk 3 above)
Comment (rigelk) [reply server/controllers/api/videos/import.ts:225]: Indeed this is a much better practice!

**Comment by Chocobozzz** [comment]
Please could you add a test in `video-imports.ts`? (please test it on your laptop, this test file is ran only once a day because of youtube errors on import).

**Comment by SimplyCorbett** [comment]
This is still an issue on the latest development branch in git.

Out of five videos (each 4k) two fail to download. Seems like a widespread problem on youtube.

**Comment by SimplyCorbett** [comment]
Actually for the above I have 4k disabled. I'm just using 480, 720, 1080 and 1440.

**Comment by rigelk** [comment]
> This is still an issue on the latest development branch in git.

What is the issue? This PR supposedly solved two.

**Comment by SimplyCorbett** [comment]
> 
> 
> > This is still an issue on the latest development branch in git.
> 
> What is the issue? This PR supposedly solved two.

Sorry! In this instance the video is still failing to download because peertube can't find the correct format. At least, I think that's whats happening. It says the video doesn't exist under logs.

**Comment by SimplyCorbett** [comment]
```

Job: 5 Type: video-import Processed on Jan 17, 2021, 7:58:45 AM Finished on Jan 17, 2021, 7:59:18 AM
--
{   "type": "youtube-dl",   "videoImportId": 5,   "generateThumbnail": false,   "generatePreview": false,   "fileExt": ".webm",   "mergeExt": ".mkv" }
Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/04c64d2a34da3b684e161455115df8cb316bb8d1f897fd64b32c11dfff883121-import.mkv'
```

**Comment by rigelk** [comment]
> > > This is still an issue on the latest development branch in git.
> > 
> > What is the issue? This PR supposedly solved two.
> 
> Sorry! In this instance the video is still failing to download because peertube can't find the correct format. At least, I think that's whats happening. It says the video doesn't exist under logs.

URLs or it didn't happen 😉

**Comment by SimplyCorbett** [comment]
Here's an example - https://youtu.be/4ufCPCwGUtQ

examplepreview

**Comment by SimplyCorbett** [comment]
Here is another:

https://www.youtube.com/watch?v=JjJHOYIVO98

**Comment by SimplyCorbett** [comment]
I'm also not able to get any 1440p60 videos to download. They all fail.

https://www.youtube.com/watch?v=2BHKshqoN60

**Comment by Chocobozzz** [comment]
@SimplyCorbett  please try https://github.com/Chocobozzz/PeerTube/commit/969e59d17d584baf695cf9a7d6122283518386a7

**Comment by SimplyCorbett** [comment]
Alright, so that fixed the issues with the above videos.

But when we circle back around to videos like this one which had washed out colors:

https://www.youtube.com/watch?v=nhym0fLkEFg

It fails to download.

If the 4k file doesn't have the proper format, maybe it should default to 1440p instead or go to the resolution that does have the format peertube needs.

**Comment by rigelk** [comment]
> https://www.youtube.com/watch?v=nhym0fLkEFg
> 
> It fails to download.

What is the associated log saying?

**Comment by SimplyCorbett** [comment]
> 
> 
> > https://www.youtube.com/watch?v=nhym0fLkEFg
> > It fails to download.
> 
> What is the associated log saying?

```
audit[1/18/2021, 9:13:07 AM]By anonymous ->video-imports -> create

{
  "user": "anonymous",
  "domain": "video-imports",
  "action": "create",
  "video-import-id": 37,
  "video-import-targetUrl": "https://www.youtube.com/watch?v=nhym0fLkEFg",
  "video-import-video-name": "Kal-El vs Justice League | Justice League [UltraHD, HDR]"
}

audit[1/18/2021, 9:13:09 AM]By anonymous ->videos -> update

{
  "user": "anonymous",
  "domain": "videos",
  "action": "update",
  "video-tags": [
    "Amy Adams (Lois Lane)",
    "Justice League (2017)",
    "Kal-El vs Justice League",
    "Superman vs Justice League",
    "clark kent vs justice league"
  ],
  "video-uuid": "2b4af3e2-48a1-4fab-ba6d-5ad60eb0e1c3",
  "video-id": 37,
  "video-createdAt": "2021-01-18T17:13:04.477Z",
  "video-updatedAt": "2021-01-18T17:13:04.477Z",
  "video-publishedAt": "2021-01-18T17:13:04.141Z",
  "video-description": "Josstice League (2017)\nScene: Superman vs Justice League\nPlaylist: https://goo.gl/FCfR1C\n\nStoryline: Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince,...",
  "video-duration": 0,
  "video-isLocal": true,
  "video-name": "Kal-El vs Justice League | Justice League [UltraHD, HDR]",
  "video-thumbnailPath": "/static/thumbnails/2b4af3e2-48a1-4fab-ba6d-5ad60eb0e1c3.jpg",
  "video-previewPath": "/lazy-static/previews/2b4af3e2-48a1-4fab-ba6d-5ad60eb0e1c3.jpg",
  "video-nsfw": false,
  "video-waitTranscoding": false,
  "video-account-id": 3,
  "video-account-name": "anonymous",
  "video-channel-id": 4,
  "video-channel-name": "random",
  "video-support": null,
  "video-commentsEnabled": true,
  "video-downloadEnabled": true,
  "new-video-tags": {
    "0": "Superman vs Justice League",
    "1": "Kal-El vs Justice League",
    "2": "clark kent vs justice league",
    "3": "Amy Adams (Lois Lane)",
    "4": "Justice League (2017)"
  },
  "new-video-updatedAt": "2021-01-18T17:13:09.958Z",
  "new-video-description": "Josstice League (2017)\r\nScene: Superman vs Justice League\r\nPlaylist: https://goo.gl/FCfR1C\r\n\r\nStoryline: Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Pri...",
  "new-video-waitTranscoding": true
}

audit[1/18/2021, 9:14:25 AM]By anonymous ->video-imports -> create

{
  "user": "anonymous",
  "domain": "video-imports",
  "action": "create",
  "video-import-id": 38,
  "video-import-targetUrl": "https://www.youtube.com/watch?v=nhym0fLkEFg",
  "video-import-video-name": "Kal-El vs Justice League | Justice League [UltraHD, HDR]"
}
```

```
error[1/18/2021, 9:13:14 AM] Cannot execute job 37 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 37,
    "generateThumbnail": false,
    "generatePreview": false,
    "fileExt": ".webm",
    "mergeExt": ".webm"
  },
  "err": {
    "stack": "Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm'",
    "message": "ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm"
  }
}

error[1/18/2021, 9:14:27 AM] Cannot execute job 38 in queue video-import.

{
  "payload": {
    "type": "youtube-dl",
    "videoImportId": 38,
    "generateThumbnail": false,
    "generatePreview": false,
    "fileExt": ".webm",
    "mergeExt": ".webm"
  },
  "err": {
    "stack": "Error: ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm'",
    "message": "ENOENT: no such file or directory, stat '/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/var/www/peertube/storage/tmp/a4d20c8fb41b9e9fd3eab6cf48eebcc8f535683869854e7913242d69e48f6795-import.webm"
  }
}
```

**Comment by rigelk** [comment]
Thanks @SimplyCorbett. @Chocobozzz sounds like depending on the merge, it's either mkv or webm. My guess is that webm video + webm audio = webm, but anything else like an m4a audio leads to a mkv container in the merge.

**Comment by Chocobozzz** [comment]
Could you try https://github.com/Chocobozzz/PeerTube/commit/805b8619c1b8c56e08c927d93293c06e1075b50d?

**Comment by SimplyCorbett** [comment]
The latest git build appears to be working! I'll let you know if I run into any problems.

**Comment by vid-bin** [comment]
With 5.2.0 and the latest git build peertube appears to be grabbing the HDR version of videos again which are washed out.

It looks like even though vcodec!*=vp9.2 is in the youtube-dl-cli it is still grabbing vp09.02.51.10

**Comment by vid-bin** [comment]
Oh lovely, the VP9 HDR and VP9 standard both use vp09.02.51.10. Not even sure if you can do anything about this.
