### PR TITLE
render plaintext descriptions on link previews

### LINKED ISSUE #3839: URL text preview displays unrendered
**Describe the current behavior**
When sending, for example to Telegram clients, a link to a Peertube video and the description text is shown, it's shown in unrendered markdown.
irudia

**Steps to reproduce:**
1. Share a Peertube video having a markdowned description text to some other app showing preview.
2. The text displays unrendered.

**Describe the expected behavior**
The text should be rendered as on Peertube itself.

**Additional information**

* PeerTube instance: https://video.anartist.org
  * URL: https://video.anartist.org
  * version: `3.0.1`
  * NodeJS version: `8.10.0`
  * Ffmpeg version: `7:4.3.2`

This also happens with Lemmy previews: https://github.com/LemmyNet/lemmy-ui/issues/110

### PR DESCRIPTION
**Pull request by rigelk**
## Description

Render markdown then strip html tags for link previews.

## Related issues

fixes #3839

## Has this been tested?

- [x] 👍 yes, modified tests to cover the existing descriptions contained in the tests
- [x] 👍 yes, light tests as follows

Tested manually video/playlist pages with markdown descriptions (lists, emphasis, etc.) on https://socialsharepreview.com/

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Please add tests

File: server/tests/client.ts [hunk 1]
```diff
@@ -39,7 +39,8 @@ describe('Test a client controllers', function () {
   let account: Account
 
   const videoName = 'my super name for server 1'
-  const videoDescription = 'my super description for server 1'
+  const videoDescription = 'my super __description__ for *server* 1'
```
Comment (Chocobozzz) [inline server/tests/client.ts:42]: Please could you add an html tag to ensure it's correctly escaped?

**Comment by Chocobozzz** [comment]
Thanks!
