### PR TITLE
Sync channel: move the list imports button #5337

### LINKED ISSUE #5337: Sync: List imports button cut
### Describe the current behavior

The `List imports` button of the synchronization screen is cut when we resize the browser window. Depending on the language, it can make the sense hardly comprehensible.

### Steps to reproduce

1. Go to http://[instance.tld]/my-library/video-channel-syncs
2. Reduce the width of the browser window (or use responsive mode in browser devtools)

You should see the button cut as below:
list imports cut button

Especially in French, we can hardly understand what the button is meant for:
list imports cut button - french

### Describe the expected behavior

Options I see:
1. Add a tooltip can describe what the button is meant for (but the tooltip is something hardly discoverable and cannot help on mobile / tablets)
2. Move this button in the actions (but it is semantically wrong, as this button does not imply changes on the synchronization)
3. Change the layout of the table when the button begins to be cropped

Personal opinion: I think the option 2 is the most convenient and answer to the problem. Some action button in the PeerTube interface don't imply a change on the item, like viewing the stats on a video (if this example is not meant to be an exception about what is allowed to be an action):

video stats button

### Additional information

* PeerTube instance:
  * URL: localhost
  * Version: 4.3.0

* Browser name, version and platforms on which you could reproduce the bug: Firefox developer edition (106.0b6 (64 bits)) or Nightly

### PR DESCRIPTION
**Pull request by fflorent**
## Description

On channel sync screen, move the list imports button form the left of the table into the action buttons list.

## Related issues

Fixes #5337

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [x] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

## Screenshots

Previously:

list imports cut button

With the patch:

list imports in actions list

### CODE REVIEW

File: client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts [hunk 1]
```diff
@@ -44,6 +44,13 @@ export class MyVideoChannelSyncsComponent extends RestTable implements OnInit {
     this.initialize()
 
     this.videoChannelSyncActions = [
+      [
+        {
+          label: $localize`List imports`,
```
Comment (fflorent) [inline client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts:49]: Note that the button is not localized anymore.

Is there any way to get the translation back here?

Comment (Chocobozzz) [reply client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts:49]: It will when I'll update translations I think

File: client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts [hunk 2]
```diff
@@ -44,6 +44,13 @@ export class MyVideoChannelSyncsComponent extends RestTable implements OnInit {
...
+          linkBuilder: (videoChannelSync) => [ `/my-labrary/video-imports?search=videoChannelSyncId:${videoChannelSync.id}` ],
```
Comment (Chocobozzz) [inline client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts:50]: `/my-labrary/` -> typo :)

**Review by Chocobozzz — CHANGES_REQUESTED** [review]

File: client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts (hunk 2 above)
Comment (fflorent) [reply client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts]: Wow, impressive eyes :eyes:
