### PR TITLE
Fix #5744: Missing plugins-global.css + missing async

### LINKED ISSUE #5744: Missing plugins-global.css file during Peertube startup
### Describe the current behavior

When Peertube starts, some requests are failing because of a missing plugins-global.css file.
Depending on the number of plugins, and the time they take to start, Peertube can be unavailable during several seconds/minutes.

Here is the error when trying to display Peertube home page:

```
peertube_1  | [localhost:9000] 2023-04-10 12:24:42.566 error: Cannot generate HTML page. {
peertube_1  |   "err": {
peertube_1  |     "stack": "Error: ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
peertube_1  |     "message": "ENOENT: no such file or directory, open '/data/tmp/plugins-global.css'",
peertube_1  |     "errno": -2,
peertube_1  |     "code": "ENOENT",
peertube_1  |     "syscall": "open",
peertube_1  |     "path": "/data/tmp/plugins-global.css"
peertube_1  |   }
peertube_1  | }

```

I found the code that is responsible of this, and I will make a PR in a minute.

### Steps to reproduce

1. Install some plugins
2. Restart Peertube
3. Try to open peertube in a browser

### Describe the expected behavior

_No response_

### Additional information

* PeerTube instance:
  * URL:
  * Version: 5.1.0
  * NodeJS version:
  * Ffmpeg version:

### PR DESCRIPTION
**Pull request by JohnXLivingston**
## Description
On startup, people trying to display the Peertube index page could face an error, because of a missing plugins-global.css file.
There was also a missing `async` attribute on a related function.

## Related issues

See https://github.com/Chocobozzz/PeerTube/issues/5744

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

I tested it by building Peertube, and running it again.

### CODE REVIEW

File: server/lib/plugins/plugin-manager.ts [hunk 1]
```diff
@@ -516,7 +516,7 @@ export class PluginManager implements ServerHook {
 
   // ###################### CSS ######################
 
-  private resetCSSGlobalFile () {
+  private async resetCSSGlobalFile () {
```
Comment (Chocobozzz) [inline server/lib/plugins/plugin-manager.ts:519]: This method is not async

File: server/lib/client-html.ts [hunk 2]
```diff
@@ -408,7 +408,13 @@ class ClientHtml {
   }
 
   private static async addAsyncPluginCSS (htmlStringPage: string) {
-    const globalCSSContent = await readFile(PLUGIN_GLOBAL_CSS_PATH)
+    let globalCSSContent
```
Comment (Chocobozzz) [inline server/lib/client-html.ts:411]: Prefer using `pathExists` from `fs-extra` to check if the file exists, and if not you can use your log message in `.info` mode

Comment (JohnXLivingston) [reply server/lib/client-html.ts:411]: Using try{}catch() can also detect permissions issues. I can add a `pathExists`, but I suggest to keep the try{}catch(). Would it be ok for you?

Comment (JohnXLivingston) [reply server/lib/client-html.ts:411]: From the node documentation:
https://nodejs.org/api/fs.html
«Using fs.exists() to check for the existence of a file before calling fs.open(), fs.readFile(), or fs.writeFile() is not recommended. Doing so introduces a race condition, since other processes may change the file's state between the two calls. Instead, user code should open/read/write the file directly and handle the error raised if the file does not exist.»

**Comment by JohnXLivingston** [comment]
@Chocobozzz : just make a new commit taking into account your comments.
I let the try/catch (see my responses to your comments), but I also added the pathExists you requested, with a log.info message.

**Comment by Chocobozzz** [comment]
Thanks!
