### PR TITLE
Set keyframe interval for transcoding (fixes #1147)

### LINKED ISSUE #1147: Set Keyframe interval for FFmpeg
The default for mp4 is a [keyframe every 250 frames](https://sites.google.com/site/linuxencoding/x264-ffmpeg-mapping) (so about every 10 seconds). This is bad for streaming, because it's harder to change resolutions. Youtube uses a keyframe interval of [2 seconds](https://streaminglearningcenter.com/blogs/whats-the-right-keyframe-interval.html).

According to [Stack Overflow](https://superuser.com/a/1098329), this should be the correct way to set a different keyframe interval. It works fine on the command line, but fails inside Peertube.
```
command.outputOptions('-force_key_frames "expr:gte(t,n_forced*2)"')
```

We could use the `keyint` parameter instead (described in the same link), but I don't understand how it works right now.

Edit: related to #1135.

### PR DESCRIPTION
**Pull request by Nutomic**
The rebase for #1205 was quite messy, so I just applied the patch to develop instead. That broke the PR somehow, so here's the same changes again.

### CODE REVIEW

File: server/helpers/ffmpeg-utils.ts [hunk 1]
```diff
@@ -324,5 +323,16 @@ async function standard (_ffmpeg) {
 
   if (bitrate !== undefined) return localFfmpeg.audioBitrate(bitrate)
 
+  // Constrained Encoding (VBV)
+  // https://slhck.info/video/2017/03/01/rate-control.html
+  // https://trac.ffmpeg.org/wiki/Limiting%20the%20output%20bitrate
+  const targetBitrate = getTargetBitrate(resolution, fps, VIDEO_TRANSCODING_FPS)
+  localFfmpeg.outputOptions([`-b:v ${ targetBitrate }`, `-maxrate ${ targetBitrate }`, `-bufsize ${ targetBitrate * 2 }`])
```
Comment (rigelk) [inline server/helpers/ffmpeg-utils.ts]: Please remove the fixed bitrate.

Comment (Nutomic) [reply server/helpers/ffmpeg-utils.ts]: Oops, fixed.

File: server/helpers/ffmpeg-utils.ts [hunk 2]
```diff
@@ -116,28 +116,27 @@ type TranscodeOptions = {
 
 function transcode (options: TranscodeOptions) {
   return new Promise<void>(async (res, rej) => {
+    let fps = await getVideoFileFPS(options.inputPath)
```
Comment (Chocobozzz) [inline server/helpers/ffmpeg-utils.ts]: Why did you move this block? :)

File: server/helpers/ffmpeg-utils.ts [hunk 3]
```diff
@@ -199,9 +192,9 @@ function getVideoFileStream (path: string) {
  * and quality. Superfast and ultrafast will give you better
  * performance, but then quality is noticeably worse.
  */
-function veryfast (_ffmpeg) {
-  _ffmpeg
-    .preset(standard)
+async function presetH264VeryFast (ffmpeg, resolution: VideoResolution, fps: number): ffmpeg {
```
Comment (Chocobozzz) [inline server/helpers/ffmpeg-utils.ts]: Please type `ffmpeg`

File: server/helpers/ffmpeg-utils.ts [hunk 4]
```diff
@@ -220,9 +213,9 @@ function veryfast (_ffmpeg) {
 /**
  * A preset optimised for a stillimage audio video
  */
-function audio (_ffmpeg) {
-  _ffmpeg
-    .preset(veryfast)
+async function presetStillImageWithAudio (ffmpeg, resolution: VideoResolution, fps: number): ffmpeg {
```
Comment (Chocobozzz) [inline server/helpers/ffmpeg-utils.ts]: Please type `ffmpeg`

File: server/helpers/ffmpeg-utils.ts (hunk 2 above)
Comment (Nutomic) [reply server/helpers/ffmpeg-utils.ts]: Because fps is needed for the preset (just noticed that I forgot to set the parameter correctly).

File: server/helpers/ffmpeg-utils.ts (hunk 3 above)
Comment (Nutomic) [reply server/helpers/ffmpeg-utils.ts]: What do you mean? Not sure how this works in Typescript..

Comment (Nutomic) [reply server/helpers/ffmpeg-utils.ts]: Oh just noticed it, I thought you mean something about the return type.

Comment (Chocobozzz) [reply server/helpers/ffmpeg-utils.ts]: :+1:

File: server/helpers/ffmpeg-utils.ts [hunk 5]
```diff
@@ -116,28 +116,27 @@ type TranscodeOptions = {
...
+    if (options.resolution !== undefined &&
+        options.resolution < VIDEO_TRANSCODING_FPS.KEEP_ORIGIN_FPS_RESOLUTION_MIN &&
+        fps > VIDEO_TRANSCODING_FPS.AVERAGE) {
+      fps = VIDEO_TRANSCODING_FPS.AVERAGE
+    }
+
     let command = ffmpeg(options.inputPath, { niceness: FFMPEG_NICE.TRANSCODING })
                     .output(options.outputPath)
-                    .preset(standard)
+    presetH264(command, options.resolution, fps)
```
Comment (rigelk) [inline server/helpers/ffmpeg-utils.ts]: you need to assign the returned 'command' instance. Also `presetH264` is now `async function`, so you need to prefix its call with `await`.

Comment (Nutomic) [reply server/helpers/ffmpeg-utils.ts]: Done. Although the return value isn't really needed afaik, because it's still the same object.
